name: AI PR Review

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
permissions:
  contents: read  # Allows the workflow to read repository contents (e.g., code)
  pull-requests: write  # Allows the workflow to post comments on PRs and create reviews
  issues: write  # Allows the workflow to create issues or comment on them
  checks: write  # Allows the workflow to create and update check runs (optional)

jobs:
  ai-review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Fetch the latest changes from the remote
        run: git fetch origin

      - name: Get commit ID
        id: get_commit_id
        run: |
          COMMIT_ID=$(git log -n 1 --pretty=format:"%H")
          echo "Commit ID: $COMMIT_ID"
          echo "commit_id=$COMMIT_ID" >> $GITHUB_ENV

      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install openai requests

      - name: Run AI Code Review
        id: ai_review
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}  # Pass the API key to the script
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Save the diff or changed files to a file
          git diff origin/main..HEAD > pr_diff.txt
          
          # Get the PR URL from GitHub context
          pr_url="https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}"

          commit_id=${{ github.sha }}
          
          # Call the AI script and pass PR URL
          python ./ai_review.py pr_diff.txt $pr_url $commit_id
