name: AI PR Review

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  ai-review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install openai requests

      - name: Run AI Code Review
        id: ai_review
        run: |
          # Save the diff or changed files to a file
          git diff origin/main...HEAD > pr_diff.txt

          # Call the AI API (OpenAI Codex in this example)
          python ./ai_review.py pr_diff.txt
